name: setup ci

inputs:
    node-version:
        description: Version spec of node.js
        required: false

runs:
    using: composite
    steps:
        - id: detect
          shell: bash
          run: |
              NODE_VERSION_FILE=.node-version
              NODE_VERSION='${{ inputs.node-version }}'

              if [ "$NODE_VERSION" = "" ] && [ -f $NODE_VERSION_FILE ]; then
                  NODE_VERSION="$(cat $NODE_VERSION_FILE)"
              fi

              echo "node-version=$NODE_VERSION" >> "$GITHUB_OUTPUT"

        - name: setup nodejs
          uses: actions/setup-node@v4
          with:
              node-version: ${{ steps.detect.outputs.node-version }}
              cache: yarn

        - name: install dependencies
          shell: bash
          run: |
              yarn install --immutable
